server:
  addr : "localhost:8080"
wemix :
  binder : "https://dev-binder.wemix.co/"
  vks : "https://dev-vks.wemix.co/"
  webauth: "https://dev-webauth.wemix.co/"
  oauth :  "https://dev-oauth.wemix.co/"

   