server:
  addr : "localhost:8080"
wemix :
  binder : "https://dev-binder.wemix.co/"
  vks :
    url : "https://dev-vks-rest.wemix.co/"
    jwttoken : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQxMzM4OTQ0MDAsImlhdCI6MTYyOTQyNDI5Mn0.HkTFHEIDpm4Cb31k-a2IiIlH2iYprcIdqilXlCSzFMA"
  webauth: "https://dev-webauth.wemix.co/"
  oauth :  "https://dev-oauth.wemix.co/"

   