server:
  addr : "localhost:8080"
wemix :
  binder :  "https://stg-binder.wemixnetwork.com/"
  vks :  "https://dev-vks.wemix.co/"
  webauth: "https://stg-webauth.wemixnetwork.com/"
  oauth :  "https://stg-oauth.wemixnetwork.com/"